services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gamine_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./admin/backend
    volumes:
      - ./admin/backend:/app
      - static_files:/app/static
      - media_files:/app/media
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://postgres:postgres123@db:5432/gamine_db
      - DJANGO_SECRET_KEY=your_django_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,ec2-52-63-238-185.ap-southeast-2.compute.amazonaws.com,52.63.238.185
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://ec2-52-63-238-185.ap-southeast-2.compute.amazonaws.com,http://52.63.238.185
      - DB_HOST=db
      - DB_NAME=gamine_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"

  admin-panel:
    build:
      context: ./admin-panel
    volumes:
      - ./admin-panel:/app
      - admin_build:/app/build
    environment:
      - REACT_APP_API_URL=http://ec2-52-63-238-185.ap-southeast-2.compute.amazonaws.com:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  gamine-react:
    build:
      context: ./gamine-react
    volumes:
      - ./gamine-react:/app
      - gamine_build:/app/build
    environment:
      - REACT_APP_API_URL=http://ec2-52-63-238-185.ap-southeast-2.compute.amazonaws.com:8000/api
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - static_files:/var/www/static
      - media_files:/var/www/media
      - admin_build:/var/www/admin
      - gamine_build:/var/www/gamine
    depends_on:
      - backend
      - admin-panel
      - gamine-react
    restart: always

volumes:
  postgres_data:
  static_files:
  media_files:
  admin_build:
  gamine_build: 